apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "name" . }}-prometheus-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "name" . }}-prometheus-server
subjects:
- kind: ServiceAccount
  name: {{ include "prometheus.serviceAccount.server.name" . }}
  namespace: {{ .Release.Namespace }}
