{{- if .Values.prometheus.serviceAccount.server.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus.serviceAccount.server.name" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
