apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-root-cert
  namespace: cert-manager
spec:
  isCA: true
  commonName: "Local CA"
  secretName: ca-root-secret
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: local-ca
spec:
  ca:
    secretName: ca-root-secret
