# Source: gitlab/charts/nginx-ingress/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "name" . }}-nginx-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "name" . }}-nginx-ingress
subjects:
  - kind: ServiceAccount
    name: {{ include "nginx-ingress.serviceAccount.name" . }}
    namespace: {{ .Release.Namespace }}
