apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "name" . }}-nginx-ingress
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "name" . }}-nginx-ingress
subjects:
  - kind: ServiceAccount
    name: {{ include "nginx-ingress.serviceAccount.name" . }}
    namespace: {{ .Release.Namespace }}
