{{- if (index .Values "nginx-ingress").serviceAccount.create -}}
# Source: gitlab/charts/nginx-ingress/templates/controller-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nginx-ingress.serviceAccount.name" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
