kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: sandbox-local-cluster
nodes:
  - role: control-plane
  - role: control-plane
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "my-label=true"
  - role: worker
  - role: worker
