apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  labels:
    app: 'gitlab'
spec:
  chart:
    version: "9.0.0"
    values:
      global:
        edition: ce
        hosts:
          domain: ci.cluster01.ingeniouslycrazy.com
        ingress:
            "cert-manager.io/cluster-issuer": letsencrypt-staging
        appConfig:
          initialDefaults:
            signupEnabled: false
            gitlabProductUsageData: false
      certmanager-issuer:
        email: davidschneider@protonmail.ch
      prometheus:
        install: false
      gitlab-runner:
        install: false
