{{- if .Values.manager.webhook.selfSignedCert.create }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "name" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
{{- end }}
