# We don't support namespaced ingressClass yet
# So a ClusterRole and a ClusterRoleBinding is required
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ include "name" . }}-nginx
spec:
  # Must match the `--controller-class` value in the NGINX Controller Deployment,
  # configurable via:
  #   nginx-ingress.controller.ingressClassResource.controllerValue
  controller: k8s.io/ingress-nginx
