{{- if .Values.app.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.serviceAccount.name" . }}-nonroot
  namespace: {{ .Release.Namespace }}
  annotations: {{- toYaml .Values.app.serviceAccount.annotations | nindent 4 }}
{{- end }}
